packages:
  - "auth"
  - "billing"
  - "web"
  - "packages/*"
  - "examples/*"

overrides:
  postcss: ^8.5.23
  sharp: ^0.35.5
  next: 15.5.27
  source-map-js: ^1.2.2
  '@esbuild-kit/core-utils>esbuild': ^0.25.12

onlyBuiltDependencies:
  - esbuild
  - workerd
  - sharp
