/** Paddle-style docs IA — single source of truth for routes, sidebar, search + llms.txt. */

export interface DocMeta {
  slug: string;
  title: string;
  group: string;
  excerpt: string;
  keywords: string;
  readingMins: number;
  level: 'Start' | 'Build' | 'Advanced';
  updated: string;
}

export const DOC_GROUPS = [
  'Get started',
  'Integrate',
  'Identity',
  'Monetize',
  'Run & secure',
] as const;

export const DOC_PAGES: DocMeta[] = [
  // Get started
  { slug: 'introduction', title: 'Introduction', group: 'Get started', excerpt: 'What SlyxUp Stack is, how auth + billing split across two Workers, and when to use it over Clerk or Auth0.', keywords: 'overview what is platform auth billing workers d1 paddle', readingMins: 4, level: 'Start', updated: '2026-09-01' },
  { slug: 'quickstart', title: 'Quickstart', group: 'Get started', excerpt: 'From zero to authenticated users in five steps: project, key, domain, SDK, sign-up.', keywords: 'start install key domain project setup quickstart', readingMins: 5, level: 'Start', updated: '2026-09-01' },
  { slug: 'core-concepts', title: 'Core concepts', group: 'Get started', excerpt: 'Projects, users, sessions, API keys, domains and test vs live — the six nouns behind every endpoint.', keywords: 'project user session key domain environment test live mental model', readingMins: 6, level: 'Start', updated: '2026-09-01' },
  // Integrate
  { slug: 'react', title: 'React integration', group: 'Integrate', excerpt: 'SlyxUpProvider, SignIn/SignUp components and auth hooks for Vite + React apps.', keywords: 'provider hooks signin signup userbutton react vite', readingMins: 7, level: 'Build', updated: '2026-09-01' },
  { slug: 'core-sdk', title: 'Core SDK (headless)', group: 'Integrate', excerpt: 'Use @slyxup/core without our UI — sign-in, sessions, billing and server-side clients.', keywords: 'headless client auth billing checkout core sdk', readingMins: 6, level: 'Build', updated: '2026-09-01' },
  { slug: 'ui-kit', title: 'UI kit', group: 'Integrate', excerpt: 'Fifteen drop-in components, three auth layouts, theming with applyTheme or CSS variables.', keywords: 'components theme pricing admin signin ui kit', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'management-api', title: 'Management API', group: 'Integrate', excerpt: 'Manage projects, keys and domains from your server with a developer session or secret key.', keywords: 'projects keys domains management api', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  // Identity
  { slug: 'authentication', title: 'Authentication', group: 'Identity', excerpt: 'Email + password sign-up, sign-in (email or username), sign-out and first-admin bootstrap.', keywords: 'signup signin signout password username email login register', readingMins: 6, level: 'Build', updated: '2026-09-01' },
  { slug: 'oauth', title: 'OAuth (Google + GitHub)', group: 'Identity', excerpt: 'Hosted authorization-code flow with 10-minute state guard, upsert-by-email and link/unlink rules.', keywords: 'google github social redirect state callback link unlink oauth', readingMins: 6, level: 'Build', updated: '2026-09-01' },
  { slug: 'passwords-verification', title: 'Passwords & verification', group: 'Identity', excerpt: 'PBKDF2 hashing, 24h verification links, 1h reset tokens and non-enumerating email flows.', keywords: 'forgot reset verify resend email token ttl password', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'sessions', title: 'Sessions', group: 'Identity', excerpt: '32-byte tokens, 7-day expiry, dual HttpOnly cookies vs Bearer — plus revoke rules.', keywords: 'cookie session bearer expiry revoke device authorize login', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'two-factor', title: 'Two-factor auth (TOTP)', group: 'Identity', excerpt: 'Authenticator setup → confirm → challenge sign-in, with recovery codes and disable rules.', keywords: 'totp authenticator challenge recovery 2fa', readingMins: 6, level: 'Advanced', updated: '2026-09-01' },
  { slug: 'users-members', title: 'Users & members', group: 'Identity', excerpt: 'Per-project search, roles (owner/admin/member), block with instant revoke, delete.', keywords: 'role admin member block delete paginate users', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'api-keys', title: 'API keys', group: 'Identity', excerpt: 'pk_ vs sk_, project-controlled test/live mode, create-once lifecycle, listing without leaks, rotation order.', keywords: 'publishable secret pk sk prefix hash rotate environment keys', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'domains-cors', title: 'Domains & CORS', group: 'Identity', excerpt: 'Origin allowlisting, www-normalization, localhost always allowed, 60s KV cache.', keywords: 'origin allowlist cors browser localhost https domains', readingMins: 4, level: 'Build', updated: '2026-09-01' },
  // Monetize (Paddle-grade)
  { slug: 'billing-overview', title: 'Billing overview', group: 'Monetize', excerpt: 'How the Paddle-backed billing Worker stays separate from auth — and the subscribe → webhook → entitlements loop.', keywords: 'billing paddle subscription plans overview money', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'plans', title: 'Plans', group: 'Monetize', excerpt: 'Plan shape (amount, interval, trial, features), active-only public listing, admin CRUD + Paddle price sync.', keywords: 'plans pricing create update deactivate paddle price', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'checkout', title: 'Checkout (Paddle)', group: 'Monetize', excerpt: 'Hosted checkout via POST /v1/billing/checkout, overlay vs redirect, success-URL verification — never trust bare params.', keywords: 'checkout paddle overlay transaction success url', readingMins: 6, level: 'Build', updated: '2026-09-01' },
  { slug: 'subscriptions-invoices', title: 'Subscriptions & invoices', group: 'Monetize', excerpt: 'Status polling, cancel-at-period-end, resume, invoice listing — and the 501 Billing-not-configured case.', keywords: 'subscription cancel resume invoice status trial', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'entitlements', title: 'Entitlements & access', group: 'Monetize', excerpt: 'Gate features server-side with getEntitlements — never trust client state or checkout params.', keywords: 'entitlements features access gate authorization paywall', readingMins: 4, level: 'Advanced', updated: '2026-09-01' },
  { slug: 'paddle-setup', title: 'Paddle setup', group: 'Monetize', excerpt: 'Connect sandbox then production: API key, client token, webhook secret, price mapping, go-live checklist.', keywords: 'paddle sandbox production webhook secret setup configure', readingMins: 7, level: 'Advanced', updated: '2026-09-01' },
  { slug: 'webhooks', title: 'Webhooks', group: 'Monetize', excerpt: 'Auth events (user.*, session.*, 2fa.*) vs Paddle subscription events — verify, respond 200 fast, work async.', keywords: 'events paddle user created billing notify endpoint signature webhooks', readingMins: 5, level: 'Advanced', updated: '2026-09-01' },
  // Run & secure
  { slug: 'self-hosting', title: 'Self-hosting', group: 'Run & secure', excerpt: 'Deploy auth + billing Workers, run D1 migrations, claim the first admin, host this panel.', keywords: 'deploy wrangler d1 secrets dev vars cloudflare selfhost', readingMins: 7, level: 'Advanced', updated: '2026-09-01' },
  { slug: 'security', title: 'Security model', group: 'Run & secure', excerpt: 'HttpOnly sessions, PBKDF2 passwords, hashed keys, origin-checked publishable keys, instant block-revoke.', keywords: 'sessions password pbkdf2 keys block https hash security', readingMins: 4, level: 'Advanced', updated: '2026-09-01' },
  { slug: 'api-reference', title: 'API reference', group: 'Run & secure', excerpt: 'Every shipped endpoint grouped by auth, users, keys, domains, OAuth, billing — with base URLs and auth scheme.', keywords: 'endpoints rest users keys projects domains oauth api reference', readingMins: 10, level: 'Advanced', updated: '2026-09-01' },
  { slug: 'troubleshooting', title: 'Troubleshooting', group: 'Run & secure', excerpt: 'Fix 401/403, CORS rejections, expired links and forced password changes — with curl reproduction tips.', keywords: 'error 401 403 cors faq debug fix troubleshooting', readingMins: 5, level: 'Build', updated: '2026-09-01' },
  { slug: 'integration-guide', title: 'Complete integration guide', group: 'Run & secure', excerpt: 'Source-accurate recipes, session transport choices and upgrade notes — downloadable as Markdown for your agent.', keywords: 'ai implementation migration sdk server spa cookie billing setup guide', readingMins: 12, level: 'Advanced', updated: '2026-09-01' },
];

export function getDoc(slug: string | undefined): DocMeta | undefined {
  return DOC_PAGES.find((d) => d.slug === slug);
}

export function docsInGroup(group: string): DocMeta[] {
  return DOC_PAGES.filter((d) => d.group === group);
}

export function prevNext(slug: string): { prev?: DocMeta; next?: DocMeta } {
  const i = DOC_PAGES.findIndex((d) => d.slug === slug);
  if (i < 0) return {};
  return {
    prev: i > 0 ? DOC_PAGES[i - 1] : undefined,
    next: i < DOC_PAGES.length - 1 ? DOC_PAGES[i + 1] : undefined,
  };
}

/** Condensed Markdown per page for "Copy for LLM" — kept in sync with the TSX sections. */
export const DOC_MARKDOWN: Record<string, string> = {
  introduction: `# SlyxUp Stack — Introduction\n\nOpen-source auth + billing on Cloudflare Workers. MIT licensed.\n\n- Auth Worker (Hono + D1 + KV): /v1/* identity API — users, sessions, keys, domains, OAuth.\n- Billing Worker (Hono + separate D1 + Paddle): plans, checkout, subscriptions, invoices.\n- Web (this site): admin panel (/admin) + public docs (/docs) + live UI kit (/ui).\n- SDKs: @slyxup/core (headless client) + @slyxup/ui (15 React components).\n\nBilling never writes to the auth DB — it validates sessions read-only. Use SlyxUp when you want Clerk-like DX but own your data (D1/SQLite) with Paddle-native billing instead of seat pricing.`,
  quickstart: `# Quickstart\n\n1. Sign in to the admin panel and create a project (slug: lowercase, numbers, hyphens).\n2. Project → Keys → create a publishable key (pk_...) for the browser. The project test/live environment controls its behavior.\n3. Project → Domains → add your origin (bare host, e.g. app.example.com; localhost always allowed).\n4. pnpm add @slyxup/core @slyxup/ui; wrap app in SlyxUpProvider with publishableKey + apiUrl + billingApiUrl.\n5. Render <SignIn /> — new users appear under Project → Users where you can edit/block/delete.`,
  'core-concepts': `# Core concepts\n\n- Project: isolation boundary owning users, keys, domains, billing plans.\n- User: end-user of YOUR product (email, names, username, role user|admin, verified, blocked).\n- Session: 32-byte token, 7-day expiry, HttpOnly cookies (+ optional Bearer).\n- API key: pk_ (browser, origin-checked) or sk_ (server only), test or live. Only SHA-256 hash stored.\n- Domain: browser origin allowlisted per project.\n- Environment: test (lenient) vs live (strict CORS/billing/rate limits).`,
  react: `# React integration\n\n<SlyxUpProvider publishableKey apiUrl billingApiUrl tokenStorage="sessionStorage"> wraps <SignIn social={false} onSuccess/> + <UserButton/>.\nHooks: useAuth, useUser, useSession, useBilling, usePlans, useSubscription, useTwoFactor. Provider client via useAuth().client; use client.getToken() for your own API bearer header. Never send tokens to untrusted URLs.`,
  'core-sdk': `# Core SDK\n\nnew SlyxupClient({ publishableKey, apiUrl }) → auth.signUp/signIn/signOut, users.me. createBillingClient({ apiUrl, publishableKey, getToken }) → listPlans, checkout, getSubscription, getEntitlements. Server admin: SlyxupClient({ secretKey }) — never in browser code.`,
  'ui-kit': `# UI kit\n\n15 components: SignIn, SignUp, UserButton, UserProfile, ForgotPassword, ResetPassword, EmailVerification, SocialButtons, BillingPortal, PricingTable, AdminPanel, PasswordField, PasswordStrength (+passwordScore), OtpInput, CopyField, EmptyState. Theme via applyTheme({ mode, accent, font, radius, primary, density }) or CSS vars on .slyxup-root (--slx-accent, --slx-radius).`,
  'management-api': `# Management API\n\ncurl -H "Authorization: Bearer <session>" $AUTH/v1/projects; GET /v1/keys?projectId=; POST /v1/keys { projectId, name, type }; DELETE /v1/keys/:id; PATCH /v1/projects/:id/domains { action: add|remove, domain }. Developer must be a project member (403 otherwise).`,
  authentication: `# Authentication\n\nPOST /v1/auth/sign-up { email, password 8-128, firstName?, username? 3-30 } → session + 24h verification email (best-effort). POST /v1/auth/sign-in { email|username, password } → { sessionToken } or { challengeToken } for 2FA accounts. POST /v1/auth/sign-out ends session + clears cookies. First admin: POST /v1/setup/bootstrap (no default password).`,
  oauth: `# OAuth\n\nGET /v1/oauth/:provider(google|github)?redirect_url=... → 10-min state → provider → /v1/oauth/callback/:provider validates single-use state, exchanges code, upserts user by verified email. Failures → /sign-in?error=missing_code|invalid_state|state_mismatch. GET /v1/user/accounts lists links; DELETE /v1/user/accounts/:id requires keeping ≥1 sign-in method.`,
  'passwords-verification': `# Passwords & verification\n\nPBKDF2-HMAC-SHA-256 (100k, per-user salt), 8-128 chars. Non-enumerating: unknown emails still return success. Verify: GET /v1/verification/confirm?token (24h) | POST /v1/verification/verify | POST /v1/verification/resend. Reset: POST /v1/verification/password/forgot { email } → 1h single-use link → POST /v1/verification/password/reset { token, password }. Rotate signed-in: POST /v1/user/password.`,
  sessions: `# Sessions\n\n32-byte token, 7-day expiry, cookies slyxup_session + __Host-slyxup_session (host-only preferred) + optional Authorization: Bearer (wins). HttpOnly Secure SameSite=Lax. Endpoints: POST sign-in, POST sign-in/2fa, POST sign-out, GET /v1/auth/session, GET /v1/sessions, DELETE /v1/sessions/:id. Block deletes all sessions. No refresh tokens — sign in again on expiry.`,
  'two-factor': `# Two-factor (TOTP)\n\nGET /v1/user/2fa/setup → { secret, uri } (not persisted; render QR). POST /v1/user/2fa/enable { secret, code } → recovery codes (show once). Sign-in returns { challengeToken } → POST /v1/auth/sign-in/2fa { challengeToken, code }. Manage: GET status, POST verify (no state change), POST disable (needs current code, emits 2fa.disabled). SignIn UI handles challenge automatically.`,
  'users-members': `# Users & members\n\nGET /v1/projects/:id/users?q=&limit(50,max200)&offset= (total for paging) + GET .../users/:userId (sessions count, OAuth providers). Roles: owner (only deleter), admin, member/user. PATCH .../users/:userId edits profile/role. Block POST .../block { reason? } deletes all sessions instantly; unblock POST .../unblock; DELETE removes everything permanently.`,
  'api-keys': `# API keys\n\npk_ (browser, origin-checked) vs sk_ (server only, never ship); test (lenient) vs live (strict). POST /v1/keys returns full key once — only SHA-256 hash stored. GET /v1/keys?projectId= lists id/name/prefix/type/env (never hashes). DELETE /v1/keys/:id revokes instantly. Rotate: create replacement → deploy → revoke old.`,
  'domains-cors': `# Domains & CORS\n\nOrigin must be allowlisted or API answers without CORS headers. Hostnames lowercase exact match, leading www. ignored. Only https:// custom origins; localhost any port always allowed. Only live-project domains enforced; KV-cached 60s (fresh adds take ~1 min). OPTIONS → 204 with credentials. Manage: PATCH /v1/projects/:id/domains { action, domain } with bare hosts.`,
  'billing-overview': `# Billing overview\n\nBilling Worker (Paddle) is separate from auth: owns plans/subscriptions/invoices, validates sessions read-only. Loop: list plans → POST /v1/billing/checkout { planId, successUrl } → open checkoutUrl (Paddle) → subscription.created webhook creates the row → GET subscription/invoices → getEntitlements gates features server-side. Unconfigured Paddle → 501 Billing not configured (plans still list).`,
  plans: `# Plans\n\nShape: name, amount (cents), currency, interval month|year, trialDays?, features[], popular, sortOrder. Public GET /v1/billing/plans?projectId= lists active only. Admin (BILLING_ADMIN_SECRET): POST/PATCH/DELETE /v1/admin/plans (+ POST .../:id/sync to create the Paddle price). Order by sortOrder; mark one popular for PricingTable highlight.`,
  checkout: `# Checkout\n\nPOST /v1/billing/checkout { planId, successUrl } → { checkoutUrl, transactionId }. Refuses when already active/trialing (cancel first). Open checkoutUrl (Paddle overlay via clientToken from GET /v1/billing/config, or hosted redirect fallback). successUrl should point at /checkout/success?transaction_id=... then VERIFY via GET /v1/billing/transactions/:id (paid flag) — never trust bare URL params. Webhook subscription.created is the source of truth for the row.`,
  'subscriptions-invoices': `# Subscriptions & invoices\n\nGET /v1/billing/subscription?projectId= (status, period, cancel flag). POST .../subscription/cancel?projectId= cancels at period end (access continues). POST .../subscription/resume?projectId= undoes it. GET /v1/billing/invoices?projectId= newest first, limit 50 (max 100). Trialing counts as subscribed for checkout refusal.`,
  entitlements: `# Entitlements\n\nServer-side: billing.getEntitlements(projectId) → { features[] } from the active subscription's plan. if (!features.includes("export")) return 403. Never gate on client state, localStorage, or checkout URL params — always re-check on each request. Use for paywalls, usage limits, plan-gated routes.`,
  'paddle-setup': `# Paddle setup\n\n1. Paddle sandbox: API key + client token + webhook secret → billing secrets (wrangler secret put). 2. Create plan in admin → auto-creates sandbox price (or paste paddlePriceId) → verify in Paddle dashboard. 3. Webhook endpoint → billing worker URL; subscribe to subscription.created/updated/cancelled + transaction.completed. 4. Test checkout end-to-end in sandbox. 5. Repeat for production env, flip project to live, re-verify. Prices and environments must match (sandbox price ≠ production).`,
  webhooks: `# Webhooks\n\nAuth events: user.created/updated/deleted, user.signed_in/signed_out, session.revoked, password.changed/reset, email.verified, oauth.linked/unlinked, 2fa.enabled/disabled → POST signed JSON to project webhook URL; verify with sk_, respond 200 fast, heavy work async. Paddle events → billing worker only; update subscriptions/invoices. Auth DB never written by billing.`,
  'self-hosting': `# Self-hosting\n\nNeeds Cloudflare account + wrangler. Auth: cd auth; cp .env.example .dev.vars; set D1/KV ids; pnpm db:generate && db:migrate:local; wrangler secret put SESSION_SECRET; wrangler dev|deploy. First admin: GET /v1/setup/status then POST /v1/setup/bootstrap (BOOTSTRAP_SECRET/BOOTSTRAP_ADMIN_EMAIL optional). Web: cp .env.example .env (VITE_API_URL), pnpm build, wrangler deploy --config wrangler.stack-frontend.jsonc. Secrets only via wrangler secret put; local via gitignored .dev.vars.`,
  security: `# Security\n\nSessions: HttpOnly Secure SameSite cookies, JS never sees tokens. Passwords: PBKDF2-HMAC-SHA-256 100k + salt; tokens crypto.randomUUID (never Math.random). Keys: SHA-256 hashed, full key in create response only. pk_ origin-checked; sk_ server-only (leak → revoke + rotate). Blocked users lose all sessions instantly. Secrets via wrangler secret put, never wrangler.jsonc/.env/git.`,
  'api-reference': `# API reference\n\nBases: AUTH (identity) + BILLING (money). Auth: Authorization: Bearer <session> or HttpOnly cookie. Auth: sign-up/sign-in/sign-out/session, user get/patch, sessions list/revoke, verification verify/resend + password forgot/reset, projects CRUD + go-live + domains + GET /v1/projects/:id/audit (timeline + total), users search/get/patch/block/unblock/delete, keys list/create/revoke, oauth start/callback + accounts, 2fa setup/enable/status/verify/disable. Billing: plans list, checkout, subscription get/cancel/resume, invoices, transactions verify, config, GET /v1/billing/stats (subscribers/MRR/revenue/per-plan); admin plans CRUD + sync. Errors: { ok:false, error } with HTTP status.`,
  troubleshooting: `# Troubleshooting\n\n401: check transport (memory vs sessionStorage vs cookie), getToken for standalone billing clients, expired → sign in again. 403: not a project member. CORS: origin in Domains + pk_ key (sk_ rejected in browsers). Invalid link: single-use + expired → resend, same browser, within window. mustChangePassword → POST /v1/auth/password/force-change. Still stuck: curl -v, paste { ok:false, error } into github.com/slyxup/stack issue.`,
  'integration-guide': `# Integration guide\n\nTransport table: SPA → SlyxUpProvider (+sessionStorage); SSR → same-origin server routes + request-scoped SlyxupClient + app-owned HttpOnly cookie; Worker API → validate bearer then enforce ownership; admin → SlyxupClient({ secretKey }) server-only. pk_ identifies project (not user); session identifies user; sk_ administers (never billing shortcut). Keep prod/staging in separate projects. Billing owns D1; no client.billing namespace in auth SDK. No shipped CLI. manageApi needs developer session token. See full downloadable Markdown in-app.`,
};
